{{- if and .Values.hubble.enabled .Values.hubble.relay.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: hubble-relay
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: hubble-relay
spec:
  type: ClusterIP
  selector:
    k8s-app: hubble-relay
  ports:
  - protocol: TCP
    port: {{ include "relay.servicePort" $ }}
    targetPort: {{ .Values.hubble.relay.listenPort }}
{{- end }}
